# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: cloudkeeper.proto for package 'cloudkeeper_grpc'

require 'grpc'
# require 'cloudkeeper_pb'

module CloudkeeperGrpc
  module Communicator
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'cloudkeeper_grpc.Communicator'

      rpc :PreAction, Google::Protobuf::Empty, Google::Protobuf::Empty
      rpc :PostAction, Google::Protobuf::Empty, Google::Protobuf::Empty
      rpc :AddAppliance, Appliance, Google::Protobuf::Empty
      rpc :UpdateAppliance, Appliance, Google::Protobuf::Empty
      rpc :UpdateApplianceMetadata, Appliance, Google::Protobuf::Empty
      rpc :RemoveAppliance, Appliance, Google::Protobuf::Empty
      rpc :RemoveImageList, ImageListIdentifier, Google::Protobuf::Empty
      rpc :ImageLists, Google::Protobuf::Empty, stream(ImageListIdentifier)
      rpc :Appliances, ImageListIdentifier, stream(Appliance)
      rpc :RemoveExpiredAppliances, Google::Protobuf::Empty, Google::Protobuf::Empty
    end

    Stub = Service.rpc_stub_class
  end
end
